services:
  reader:
    build: .
    container_name: vision-reader
    restart: unless-stopped
    environment:
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_USER: ${MQTT_USER}
      MQTT_PASS: ${MQTT_PASS}
      LOG_LEVEL: ${LOG_LEVEL}
      APP_DEBUG: ${APP_DEBUG}
      #POLL_INTERVAL_S: "3"
    volumes:
      - ./config:/app/config
      - ./state:/app/state
      - ./paddle_cache:/root/.paddleocr
    command: ["python", "-u", "app/main.py"]

  roi-web:
    build: .
    container_name: roi-web
    restart: unless-stopped
    ports:
      - "8088:8088"
    environment:
      LOG_LEVEL: INFO
    volumes:
      - ./config:/app/config
    command: ["python", "-u", "roi_web/server.py"]
