global:
  poll_interval_s: 9
  conf_threshold: 0.6
  roi_upscale: 2
  max_step_kwh: 50      # <- nový limit na jednorazový skok
sensors:
- id: electricity_main
  snapshot_url: http://192.168.30.104:8080/shot.jpg
  mqtt_topic_base: ha/electricity
  roi_display:
  - 161
  - 728
  - 320
  - 105
  initial_t1: 13413
  initial_t2: 17588
