global:
  poll_interval_s: 9           # ako často čítať snapshot
  conf_threshold: 0.60         # minimálne confidence
  roi_upscale: 2               # 1–3 (Paddle má rád väčšie ROI)

sensors:
  - id: "electricity_main"
    snapshot_url: "http://192.168.30.104:8080/shot.jpg"
    mqtt_topic_base: "ha/electricity"
    roi_display: [154, 729, 322, 98]   # x,y,w,h
    initial_t1: 0                      # v kWh ako celé číslo displeja
    initial_t2: 0

